### ISSUE TITLE
Shift-Clicking in the Discoveries GUI should take a stack of items

### ISSUE THREAD

**Issue by MrJoCrafter** [Chew/TransmuteIt#17] opened 2020-03-23 16:29 UTC
**Is your feature request related to a problem? Please describe.**
It's frustrating and spammy to take one item at a time.

**Describe the solution you'd like**
I would like to be able to shift-click 64 items out of this GUI

**Describe alternatives you've considered**
Or... a button in the GUI to switch to 'stack mode' which would do the same thing.

**Comment by Chew** [comment] 2020-03-23 16:30
Did you read the changelog? This was added (duplicate of #9), released as of build 20, (we're on 22)

**Closed as completed by Chew** 2020-03-23 16:30 UTC
Labels: duplicate
